listen=YES
listen_ipv6=NO
background=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=002
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/srv/ftp/web
pam_service_name=vsftpd
seccomp_sandbox=NO
secure_chroot_dir=/var/empty
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
connect_from_port_20=NO
